### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by SyncStelar** [MCMi460/NSO-RPC#10]
The program crashes after inputting the link and pressing the "Log In" button. Running the debug tool yields no result and there is no folder/file created at /Documents.

**Comment by MCMi460** [comment]
Wow, this baffles me. When you run `cli.py`/`app.py`, does Python just hang there, or does it immediately end the program?
Also, how does the program react if you clone the repository at `origin/development` (the most recent branch) and run the `app.py` in there? If an `NSO-RPC/` folder is created at `~/Documents/`, could you paste the contents of `NSO-RPC/logs.txt` here?
I'm going to attempt to get both Windows 11 and Linux later today on a second computer so I can actually bug test these sort of things. Both of these operating systems are somewhat foreign to me, so understanding exactly what is going wrong is difficult currently.

**Comment by MCMi460** [comment]
Due to inactivity, I'm going to close this issue for the moment.
