### ISSUE TITLE
unhandled exception in script

### ISSUE THREAD

**Issue by GeetaArmstrong** [MCMi460/NSO-RPC#108]
I've been having this issue for a while now, tried downloading it again and it still doesn't work.
![image](https://github.com/MCMi460/NSO-RPC/assets/15623645/fca66621-25da-4afb-bd91-fb70cefd2954)

**Comment by HotaruBlaze** [comment]
Delete everything inside of `Documents\NSO-RPC` and re-launch NSO-RPC

**Comment by GeetaArmstrong** [comment]
> Delete everything inside of `Documents\NSO-RPC` and re-launch NSO-RPC

thank you!
