### ISSUE TITLE
Application crashes, followed by Error Text

### ISSUE THREAD

**Issue by JoeMcStinky** [MCMi460/NSO-RPC#113]
When I open a fresh installation of NSO-RPC.exe (after deleting the folder in my Documents), once I paste the copied text I got from the Pop-Up, the application crashes, and upon re-opening, it shows an error screen with this text:

Traceback (most recent call last):
  File "cli.py", line 85, in update
    'user_lang': self.api.user_lang,
    ^^^^^^^^^^^^^^^^^^
  File "api\__init__.py", line 162, in getSelf
  File "api\__init__.py", line 175, in getFriends
  File "api\__init__.py", line 340, in populateList
  File "api\__init__.py", line 337, in populateList
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "api\__init__.py", line 151, in updateLogin
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 764, in <module>
  File "app.py", line 303, in selfService
  File "app.py", line 422, in changeState
  File "app.py", line 419, in changeState
  File "cli.py", line 91, in update
    log(e)
  File "api\__init__.py", line 153, in updateLogin
Exception: Failure with authorization: 'result'
Login returns {'status': 9403, 'errorMessage': 'Invalid token.', 'correlationId': '0c84736a-0bd46d00'}

What am I doing wrong?
Some things that might help:
- The text that I copy over from the 'Select this Person' box is not a URL, but a string of letters and numbers that mentions 'session_token_code's and 'session_state's (looks kinda like keysmashing/BASE64)
- NSO-RPC has worked in the past, though I have not used it since around September

- also I am not an expert in Python, frankly I'm below amateur-level, so if this is some fix i'd have to mess around in cmd to fix that doesn't have some copypaste text i can slap in, than please let me know, close this issue, and I'll check out the next Update to see if it works for me again. Hope someone can help me out with this!

**Comment by HotaruBlaze** [comment]
I'm just reposting this from discord as I've already supplied a current fix in #support on discord

---
1. Grab the build from here: <https://github.com/HotaruBlaze/NSO-RPC/releases/tag/b1.4.1>
2. Delete private.txt and tempToken.txt from `Documents\NSO-RPC`
3. Open settings.txt in a text editor and add the following `, "overrideVersion": "2.7.1"`.
**Remember to add the comma before "overrideVersion"**

you should end up with something like below
```json
{"dark": true, "startInSystemTray": false, "startOnLaunch": false, "smallImagePFP": true, "friendcode": "", "overrideVersion": "2.7.1"}
```

Now launch NSO-RPC and it should ask you to relink your account, afterwards it should work as intended

---
#112 is related to the issue and supplying the above temp workaround.

**Comment by JoeMcStinky** [comment]
LET'S GO IT WORKED, THANK YOU VERY MUCH HOTARUBLAZE!
