### ISSUE TITLE
Nintendo eShop Button

### ISSUE THREAD

**Issue by Nictune** [MCMi460/NSO-RPC#118]
Will there be further updates to the eShop link? I noticed for a lot of my games that when the button is selected, the link directs to an invalid page. If not that then could it possibly be hidden for games that aren't supported? Love the work you have done! <3

**Comment by MCMi460** [comment]
Sorry! Didn't see this before.
If you'd like, I can add a manual toggle for the eShop button, but links are provided by Nintendo, so short of GETing the link every time it's returned, I don't have a good way of telling if it's valid or not.

**Comment by Nictune** [comment]
Hi! No worries at all! I realized that it’s nothing to do with the NSO-RPC itself. Long story short, I have my Japanese account connected as the primary. Therefore, it will link to the JP website (which looks SO much better than US btw) so if I go to the eShop on my console, some of the games I have show on my end as purchased in both my US account and my JP account. Those are the ones that work properly, but there are some other games where if it is purchased in either the JP or US store, they will be separate applications. These are the ones that typically won’t show. I hope I explained that properly haha. Also, yes! The toggle would be perfect! Just for consistency, you know?Also, had another question while I have you! Is there a way to show the game name under your Discord name when the status is up? Instead of it showing “Playing Nintendo Switch” it would show “Playing The Legend of Zelda: Tears of the Kingdom”. No worries if not! This is a wonderful tool! 💜On Jan 22, 2024, at 5:48 PM, Deltaion Lee ***@***.***> wrote:﻿
Sorry! Didn't see this before.
If you'd like, I can add a manual toggle for the eShop button, but links are provided by Nintendo, so short of GETing the link every time it's returned, I don't have a good way of telling if it's valid or not.

**Comment by MCMi460** [comment]
Ah, that makes sense.
Also, as for your suggestion, it's a feature I'm planning on the next iteration of NSO-RPC, but it may take some time before it's finished.
Sorry for the inconvenience!

**Comment by Nictune** [comment]
No problem at all. Glad to know it's in the works! Also, do I need to update NSO-RPC myself? Or does it get updated automatically? Just so I can keep a lookout for the toggle. (Sorry, new to GitHub.)

**Comment by MCMi460** [comment]
You'll need to update yourself. Do you have a Discord account? If so, I can send you the new build when I'm done with it without having to make a new release on GitHub.

[Here's the link](https://discord.gg/pwFASr2NKx)

**Comment by Nictune** [comment]
I do! Just accepted. Thanks again.
