### ISSUE TITLE
Random (?) crashes on Windows 11

### ISSUE THREAD

**Issue by JoshuaJSlone** [MCMi460/NSO-RPC#12]
There's not a lot of detail to give, but sometimes choosing a menu item it just crashes. I can't tell if the attempt to load the new screen is causing the crash or if it was already in a broken state and clicking anything makes the program shut down. Restarting right away works without issue. Checking the logs.txt file I can see what seem to be the successful logins when the program is launched, but don't see anything that seems useful regarding this issue in between those times.

**Comment by MCMi460** [comment]
Try directly running `app.py` and getting the error data from there- most GUI errors are not caught by `NSO-RPC/logs.txt` (an issue on my part).

**Comment by JoshuaJSlone** [comment]
Got it running that way, returned to PC after several hours, clicked on Friend List and got a crash.

Traceback (most recent call last):
  File "I:\UserFoldersJ\Downloads\NSO-RPC-1.2\NSO-RPC-1.2\client\app.py", line 428, in switchFriends
    self.updateFriends()
  File "I:\UserFoldersJ\Downloads\NSO-RPC-1.2\NSO-RPC-1.2\client\app.py", line 366, in updateFriends
    client.api.getFriends()
  File "I:\UserFoldersJ\Downloads\NSO-RPC-1.2\NSO-RPC-1.2\client\api\__init__.py", line 108, in getFriends
    list.populateList(self)
  File "I:\UserFoldersJ\Downloads\NSO-RPC-1.2\NSO-RPC-1.2\client\api\__init__.py", line 275, in populateList
    arr = json.loads(response.text)['result']['friends']
KeyError: 'result'

**Comment by MCMi460** [comment]
This is quite strange to say the least. From the error data, the most obvious conclusion is that for some reason it cannot receive a result from the API, but I can't conclude as to why.
This seems unrelated to issue #13 - the most prominent API issue currently- as when I test the app on MacOS and Windows 10, I'm still able to use the Friend List function.
I'm sure you've already checked for this, but is your internet dropping connection? When you log in, is the information it shows as your profile correct? Have you tried removing the `NSO-RPC` folder entirely and reopening the app?
You are not the first to have issues on Windows 11, it makes me wonder what has changed so much to induce such an onslaught of errors for users who use it... especially considering it isn't just a PyInstaller issue.

**Comment by JoshuaJSlone** [comment]
The Internet has been working when I launch and when I click to cause a crash, but it could've lost it sometime between if that's causing something to trip up. Both my profile and the friend list work properly when the program is first started.

**Comment by anthonybaldwin** [comment]
Maybe GUI is mad we're not logged in / #21 dupes this?

**Comment by MCMi460** [comment]
This should have been fixed in #21/#22. Thank you for bringing this to light!
