### ISSUE TITLE
"Launch Error" on M2 Mac

### ISSUE THREAD

**Issue by marmar-bit** [MCMi460/NSO-RPC#120]
Hi!
I am using an M2 (silicon) Macbook Pro and I used the latest universal installer2 to download NSO-RPC, it was working fine until it suddenly crashed as I was opening a game on the Switch, and now every time I try to open it, even after uninstalling it and reinstalling it, I get the error: "Launch Error see the py2app website for debugging launch issues" with two options, "visit website" or "terminate", and after looking at the py2app website I'm not sure what to do.
Any help is appreciated!

**Comment by HotaruBlaze** [comment]
It's probably f Calculation here being down: https://status.imink.app/

Just gotta wait, Sorry!

(We really need to handle that error properly)

**Comment by marmar-bit** [comment]
Oh okay! Thank you for your reply, I didn't know 😄
