### ISSUE TITLE
Crash on EXE Launch

### ISSUE THREAD

**Issue by Lukas-Batema** [MCMi460/NSO-RPC#121]
I have been using this app for about a week or two, worked okay, a couple of issues arose like the RPC not always starting when powering on my switch and opening a new game, but now it just refuses to open at all...

![image](https://github.com/MCMi460/NSO-RPC/assets/55695493/3e1348fa-541a-4eba-8722-927e88fad90e)

# Error
```txt
Traceback (most recent call last):
  File "cli.py", line 85, in update
  File "api\__init__.py", line 162, in getSelf
  File "api\__init__.py", line 175, in getFriends
  File "api\__init__.py", line 340, in populateList
  File "api\__init__.py", line 337, in populateList
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 764, in <module>
  File "app.py", line 303, in selfService
  File "app.py", line 422, in changeState
  File "app.py", line 419, in changeState
  File "cli.py", line 91, in update
  File "api\__init__.py", line 148, in updateLogin
  File "api\__init__.py", line 267, in __init__
KeyError: 'timestamp'
```

**EDIT**
Perhaps related to #120?

**Comment by HotaruBlaze** [comment]
`KeyError: 'timestamp'`
9/10 times this is in fact F calc API being down.

So its the same as #120

**Comment by Lukas-Batema** [comment]
> `KeyError: 'timestamp'` 9/10 times this is in fact F calc API being down.
> 
> So its the same as #120

Thanks for confirming! After I sent this, I figured that was the issue haha. I'll make another issue about the other thing I mentioned, but I'll close this issue :) cheers!

**Comment by HotaruBlaze** [comment]
> > `KeyError: 'timestamp'` 9/10 times this is in fact F calc API being down.
> > So its the same as #120
> 
> Thanks for confirming! After I sent this, I figured that was the issue haha. I'll make another issue about the other thing I mentioned, but I'll close this issue :) cheers!

For other issues such as RPC not working, I'd recommend joining the discord located at the top of the FAQ on the readme.

**Comment by Lukas-Batema** [comment]
> > > `KeyError: 'timestamp'` 9/10 times this is in fact F calc API being down.
> > > So its the same as #120
> > 
> > 
> > Thanks for confirming! After I sent this, I figured that was the issue haha. I'll make another issue about the other thing I mentioned, but I'll close this issue :) cheers!
> 
> For other issues such as RPC not working, I'd recommend joining the discord located at the top of the FAQ on the readme.

I'm already in 200 servers with nitro, that's why I figured I would here.
