### ISSUE TITLE
can't open app

### ISSUE THREAD

**Issue by Blizard0007** [MCMi460/NSO-RPC#124]
![image](https://github.com/MCMi460/NSO-RPC/assets/105304678/c2aec231-80bd-481e-8b81-ba1e7621720c)
can you help me ?

**Comment by MCMi460** [comment]
Unfortunately, [imink f token calculation API](https://status.imink.app) is down. Please wait until it is back up again.

**Comment by Blizard0007** [comment]
okay thanks

**Comment by doceazedo** [comment]
Also not opening on macOS Sonoma 14.0 running the latest NSO-RPC release 😕 I tried uninstalling normally + using App Cleaner & Uninstaller with no luck. I checked and imink seems to be up.

<img src="https://github.com/MCMi460/NSO-RPC/assets/33992396/9ca8bed8-9a41-4dfa-bf18-2d86284b1408" width="260" />

**Comment by MCMi460** [comment]
That's odd - the API is online, meaning this issue is probably unrelated.
Did you choose the right install for MacOS? I.e. Intel vs Universal?

**Comment by doceazedo** [comment]
Yep, I tried `mac-universal2-installer.dmg` and `mac-universal2-portable.zip` and even building it myself. It ran on the first time but since then it always throws this error on startup. Let me know if there is any way I can help debugging this issue further.

**Comment by MCMi460** [comment]
Have you tried deleting your `~/Documents/NSO-RPC` folder?

**Comment by doceazedo** [comment]
This did the trick, thank you! _I guess I missed that step on README, sorry 😅_ Apparently my secondary Nintendo account link makes the app crash and not open anymore, probably because it's not linked to a Switch. Will do that now, thank you once again :)

**Comment by MCMi460** [comment]
Glad I could help!
And you're definitely right about it crashing because it's not linked to a Switch. I've really got to make more comprehensive error reports.
