### ISSUE TITLE
Program not running

### ISSUE THREAD

**Issue by MotorDriven** [MCMi460/NSO-RPC#125]
Every time i open the program I get this error on windows
![oops](https://github.com/MCMi460/NSO-RPC/assets/160430791/07d34c7f-94fb-41dd-aa82-95c657c5a8cd)

**Comment by HotaruBlaze** [comment]
This usually only happens if some form of malware protection blocked it, such as Malwarebytes, or that the downloaded exe is corrupted and needs to be redownloaded.
