### ISSUE TITLE
when I try to run the build it pops up an error box that says "Windows cannot find dist make sure you typed the name correctly"

### ISSUE THREAD

**Issue by mozquit0** [MCMi460/NSO-RPC#14]

**Comment by MCMi460** [comment]
This is likely because of another error before trying to find the folder named `dist/`. Please check the console prompt and see what error pops up; it's likely related to a PyInstaller issue.

**Comment by MCMi460** [comment]
Until the issuer describes their problem with more detail, I'm closing this issue. I'm sorry for not being of much help.
