### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by Taupe** [MCMi460/NSO-RPC#144]
Hey,

I'm getting this pop-up every time I try to start NSO-RPC telling me to enter the App Store version of the NSO Mobile App. After entering the correct version (2.10.0 as of May 8, 2024), nothing happens.

![image](https://github.com/MCMi460/NSO-RPC/assets/81835593/241c79ca-d900-435d-9e23-a86fbfce43ad)

**Comment by Jiralite** [comment]
The reason why nothing happens is because of this:

https://github.com/MCMi460/NSO-RPC/blob/f6e683fe5140290108696b051ed2ae593cb4b3cc/client/api/__init__.py#L99-L102

2.10.0 does not match `\d.\d.\d` due to it only accepting a singular digit (`.` itself not being escaped is a separate issue).

**Comment by HotaruBlaze** [comment]
I'm already aware of this and dealt with it here: #145 

either do 2.9.1 and hope it wont crash, or use this build for now: https://github.com/HotaruBlaze/NSO-RPC/releases/tag/dev-ovr-2.9.1-HotaruBlaze

**Comment by Taupe** [comment]
Thanks!
