### ISSUE TITLE
Cannot build `development` branch due to autoremoved/non-existent version.txt

### ISSUE THREAD

**Issue by luni-moon** [MCMi460/NSO-RPC#148]
I tried building the development branch from source, and it failed due to version.txt missing, so I added it as blank manually. I tried again, the file was removed (seemingly due to the code from `_version.py`, regarding these lines: 
https://github.com/MCMi460/NSO-RPC/blob/ba58863114907d2b62fbf45e3407d749e4657c4b/client/_version.py#L19-L25

I was not able to get the "stable" version to work, so I did a little poking around and found issues #144 and #146. Then I looked and found that there is a PR, but not before trying a build that `HotaruBlaze` made about a week ago (which only errored out). This does not seem like an upstream error, so much help would be appreciated, as I wanted to use this while the fixes for the version entering (and probably more) was being worked on. Thank you! 

Here is my log output:
```txt
PS C:\Users\Luni\Downloads\NSO-RPC-development\NSO-RPC-development\scripts> .\build.bat
Building with PyQt6

[notice] A new release of pip available: 22.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "C:\Users\Luni\Downloads\NSO-RPC-development\NSO-RPC-development\client\_version.py", line 23, in <module>
    version_info = get_version_info()
  File "C:\Users\Luni\Downloads\NSO-RPC-development\NSO-RPC-development\client\_version.py", line 6, in get_version_info
    r = git.repo.Repo(search_parent_directories=True)
  File "C:\Users\Luni\AppData\Local\Programs\Python\Python310\lib\site-packages\git\repo\base.py", line 265, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: C:\Users\Luni\Downloads\NSO-RPC-development\NSO-RPC-development\client
529 INFO: PyInstaller: 6.3.0
529 INFO: Python: 3.10.6
536 INFO: Platform: Windows-10-10.0.19045-SP0
537 INFO: wrote C:\Users\Luni\Downloads\NSO-RPC-development\NSO-RPC-development\client\NSO-RPC.spec
540 INFO: Removing temporary files and cleaning cache in C:\Users\Luni\AppData\Local\pyinstaller
543 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Luni\\Downloads\\NSO-RPC-development\\NSO-RPC-development\\client']
914 INFO: Appending 'datas' from .spec
Unable to find 'C:\\Users\\Luni\\Downloads\\NSO-RPC-development\\NSO-RPC-development\\client\\version.txt' when adding binary and data files.
PS C:\Users\Luni\Downloads\NSO-RPC-development\NSO-RPC-development\scripts>
```

**Comment by HotaruBlaze** [comment]
I updated that code recently to fix some other issue, however I believe your real issue is below.

`git.exc.InvalidGitRepositoryError: C:\Users\Luni\Downloads\NSO-RPC-development\NSO-RPC-development\client`

This makes me think that you are running it from a zip you downloaded and not a git clone, this will not generate a working _version.txt file, as it uses git history to generate the correct tag/commit

You can either disable the _version.txt file and put your own string in for testing, or make sure you are doing a git clone and not a zip download.

`git clone -b development https://github.com/MCMi460/NSO-RPC.git`

---

version.txt is just a text string that gets embedded into the app for easier debugging.

![image](https://github.com/MCMi460/NSO-RPC/assets/17028801/8cf4cd06-dc20-4e46-9c89-cf27eb8812df)

**Comment by luni-moon** [comment]
> I updated that code recently to fix some other issue, however I believe your real issue is below.
> 
> `git.exc.InvalidGitRepositoryError: C:\Users\Luni\Downloads\NSO-RPC-development\NSO-RPC-development\client`
> 
> This makes me think that you are running it from a zip you downloaded and not a git clone, this will not generate a working _version.txt file, as it uses git history to generate the correct tag/commit
> 
> You can either disable the _version.py script and put your own string in for testing, or make sure you are doing a git clone and not a zip download.
> 
> `git clone -b development https://github.com/MCMi460/NSO-RPC.git`
> 
> version.txt is just a text string that gets embedded into the app for easier debugging.
> 
> ![image](https://private-user-images.githubusercontent.com/17028801/330644780-8cf4cd06-dc20-4e46-9c89-cf27eb8812df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NDE3MjgsIm5iZiI6MTcxNTc0MTQyOCwicGF0aCI6Ii8xNzAyODgwMS8zMzA2NDQ3ODAtOGNmNGNkMDYtZGMyMC00ZTQ2LTljODktY2YyN2ViODgxMmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAyNTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNzcwZWI5ZDRmZmNhMzEyMWI2Y2I2MGZhZThmMzYyMjI5YmEwYjYwMDA5YTVlMzQzYWFkNzY1MmZmYzVjYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sdt3t2CjY3yZM-CKvToX3ioQdpIYri06a_WuBw4JEuk)

Ah, thank you. I prefer not to do cloning (as I don't like GitHub and MSFT security stuff, nut this is better than GitLab), so that's why I do zip downloads. I'll try the aforementioned way and see if that works.

**Comment by HotaruBlaze** [comment]
https://github.com/MCMi460/NSO-RPC/blob/ba58863114907d2b62fbf45e3407d749e4657c4b/scripts/build.bat#L35-L36

May be smarter to just comment out the build step above :)

**Comment by luni-moon** [comment]
> https://github.com/MCMi460/NSO-RPC/blob/ba58863114907d2b62fbf45e3407d749e4657c4b/scripts/build.bat#L35-L36
> 
> May be smarter to just comment out the build step above :)

I couldn't find it for the life of me, but it displays RPC either way, so I guess for once programming fixes two bugs with one line(?) Okay, a bad idiom made modern...
