### ISSUE TITLE
App not detecting my game

### ISSUE THREAD

**Issue by VGmaster670** [MCMi460/NSO-RPC#15]
So I've been using the app since v1.1 and it worked fine until about two days ago when it suddenly decided to not work anymore, I noticed there was a new version so I updated the app but it doesn't seem to have fixed the issue. I initially attributed this to Nintendo Switch Sports being weird with its online status but upon trying it with other games it still doesn't work. I've tried logging out and logging back in and toggling "Update status" on and off but nothing. Maybe it's an API issue?
![20220501_135348](https://user-images.githubusercontent.com/72361126/166158410-62a2d9ea-1868-471a-80bb-d061f42b3d67.jpg)

**Comment by MCMi460** [comment]
You're correct- it is an API issue. Nintendo has stopped supporting `/v3/User/ShowSelf` as a method to retrieving one's `Presence` status.
Please see issue #13 for the development of this issue.
Thank you for the well-documented issue!
