### ISSUE TITLE
Failed to execute script 'app' due to unhandled exception: Failure with authorization: 'result'

### ISSUE THREAD

**Issue by mariofan12ify** [MCMi460/NSO-RPC#156]
I've been getting this error recently and I don't know what to do to fix it:
![image](https://github.com/MCMi460/NSO-RPC/assets/35483921/be2010c6-6434-4ed5-907a-ccef9891fb1f)

**Comment by HotaruBlaze** [comment]
Use this build until we do an new official build. the above error shouldn't show up again: 
https://github.com/HotaruBlaze/NSO-RPC/releases/tag/v1.4.1-HB
