### ISSUE TITLE
Can't run MacOS app

### ISSUE THREAD

**Issue by zeromotion461** [MCMi460/NSO-RPC#2]
I try to run the app, but a box pops up saying "app Error" with the choices to either Open Console or Terminate. I'm not sure how to fix this issue.

**Comment by MCMi460** [comment]
I'll definitely need more information to work on than this. Try cloning this repository and running the app through the command line. Please update me on anything different that occurs.
May I ask what computer model you have? It works for me on both x86_64 and arm64.

**Comment by zeromotion461** [comment]
It's a 2018 MacBook Pro with 6-core Intel Core i7

**Comment by drewv1234** [comment]
The Mac version of the app is also not working for me – any attempt to open the app results in the app crashing. I tried cloning the repository and running cli.py from Terminal and get this error: 
Error, failed after 500 attempts
'[Errno 61] Connection refused'

I'm using an Intel MacBook as well

**Comment by MCMi460** [comment]
> The Mac version of the app is also not working for me – any attempt to open the app results in the app crashing. I tried cloning the repository and running cli.py from Terminal and get this error: Error, failed after 500 attempts '[Errno 61] Connection refused'
> 
> I'm using an Intel MacBook as well

The error you're receiving is related to the client not connecting to Discord. Is Discord open on your computer?

**Comment by drewv1234** [comment]
Whoops – my mistake, that seems to have fixed the issue!

**Comment by zeromotion461** [comment]
I cloned the repository and it didn't work.

**Comment by MCMi460** [comment]
I believe this issue is no longer MacOS exclusive, so we'll have to migrate to issue #3.

**Comment by drewv1234** [comment]
Wasn't sure if this warranted a new issue, but after updating the application to the newest version, the app now gives me a splash screen with an app error.  The old version of the app still works fine when I boot it up, but this new version crashes on launch after I enter my login info. Here's the error when I run the unix executable app by expanding the contents:

Traceback (most recent call last):
  File "/Applications/app.app/Contents/Resources/__boot__.py", line 110, in <module>
    _run()
  File "/Applications/app.app/Contents/Resources/__boot__.py", line 84, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Applications/app.app/Contents/Resources/app.py", line 481, in <module>
    window.selfService()
  File "/Applications/app.app/Contents/Resources/app.py", line 147, in selfService
    self.changeState()
  File "/Applications/app.app/Contents/Resources/app.py", line 245, in changeState
    client.update()
  File "cli.pyc", line 53, in update
  File "api/__init__.pyc", line 90, in updateLogin
  File "api/__init__.pyc", line 210, in __init__
  File "api/__init__.pyc", line 186, in get
  File "json/__init__.pyc", line 346, in loads
  File "json/decoder.pyc", line 337, in decode
  File "json/decoder.pyc", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-04-26 15:15:28.761 app[1649:21366] app Error

**Comment by MCMi460** [comment]
@drewv1234 Try deleting the `NSO-RPC/` folder in your `~/Documents/` folder. You will unfortunately have to log back in after this, however. I think this is an error because of a change in formats of data storage between v1.1 and v1.2.
Please update me on if this works, thanks!

**Comment by drewv1234** [comment]
Didn't seem to work on my end. Tried deleting the app and the documents folder and it gave me the same error almost every time I ran it. However, one time it gave me the same error shown in #11 , so it might be related to that.

**Comment by samuelthomas2774** [comment]
@drewv1234 It looks like the flapg API is down at the moment (which matches your error, although #11 looks like a s2s API issue), you’ll just have to try again later.

@MCMi460 If you can login (or MITM the app) are you actually getting your own presence back properly? I haven’t today and think Nintendo may have changed their API. samuelthomas2774/nxapi#1

**Comment by MCMi460** [comment]
> @drewv1234 It looks like the flapg API is down at the moment (which matches your error, although #11 looks like a s2s API issue), you’ll just have to try again later.
> 
> @MCMi460 If you can login (or MITM the app) are you actually getting your own presence back properly? I haven’t today and think Nintendo may have changed their API. [samuelthomas2774/nxapi#1](https://github.com/samuelthomas2774/nxapi/issues/1)

Thank you for bringing this to my attention- I'm moving this issue to #13 for now, but I imagine I can't do very much to fix this on my own as I'm not a master of reverse engineering.
I will mitmproxy as soon as I get a moment to be able to. Thank you again.
