### ISSUE TITLE
the windows.zip file is a virus

### ISSUE THREAD

**Issue by Huhnxhen** [MCMi460/NSO-RPC#24]
I am really sure the windows.zip file of the latest release is a virus.

**Comment by MCMi460** [comment]
It isn't- you can refer to #7 as to why Windows Defender picks it up as one.
Also, the current release of windows.zip does not work as it has outdated headers. An alternative to using the pre-compiled release I publish is to just run the `app.py` from the main branch.
Thank you for being skeptical; most people just run the downloaded executable without care.
