### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by RepressedNerd** [MCMi460/NSO-RPC#29]
Hi!
I've been using the program on my Mac. It worked at the start pretty smoothly, but it sometimes had issues with launching, so I'd try deleting the NSO-RPC folder and it would work. However, it doesn't work anymore. I've tried deleting and reinstalling it and it still doesn't work. It launches completely fine before I log in, but after I enter the URL to log in, the app closes (I believe it's supposed to relaunch on its own?) but doesn't open up again. I know it usually takes a while, so I waited about 15 minutes for it, but it still never opened. So I tried to open it myself, and it comes up with this error:

<img width="424" alt="image" src="https://user-images.githubusercontent.com/67737702/181717199-f49fc66c-11f9-4df0-848a-3f51e9b6571d.png">

I read the page and tried opening it with Terminal, but the same issue occurred.

**Comment by MCMi460** [comment]
Have you tried the Python script `app.py` as well? It's possible the app didn't completely quit or something, so try searching in Activity Monitor for "app" or similar search terms. MacOS can have some strange things happen like this.
I'm not entirely sure what the issue is here, but I'm assuming it has something to do with py2app. You could attempt opening Console and getting the error information.
Just to make sure, you are on v1.3, right?

**Comment by RepressedNerd** [comment]
How would I use the script? I don't know anything about Python, sorry :( 
I did try looking in Activity Monitor and I couldn't find anything, so it must have been completely closed.
I also don't know how to get the error information. I can do it if you can tell me how!

A similar issue is happening on my Windows computer, wherein it works fine until I do the log in thing. On Windows, it stops responding (it says "Not Responding" and has the loading cursor thingy), and crashes. I go to open it again and it gives me what I believe is a much more detailed error dialogue, although I don't understand what it means.
Here's a screenshot:
![image](https://user-images.githubusercontent.com/67737702/181765283-17ad4b2d-626b-4113-b14c-c2dbbb8637c0.png)

And yup, I'm on 1.3. The one from the 29th of June?

**Comment by MCMi460** [comment]
Ah, I see exactly why now. The Nintendo Switch Online app has updated, and I didn't realize it had since I've been using the latest version on the development branch. I'll recompile and publish v1.3.1 later today.
Sorry for the inconvenience.

**Comment by samuelthomas2774** [comment]
@MCMi460 I've set up a repository to fetch the latest versions from iTunes, Google Play and Nintendo's EU/JP websites: https://github.com/samuelthomas2774/nintendo-app-versions. I'm not sure if there's any way to get notifications for commits on GitHub directly (I don't think watching the repository does that), but new commits are published in my Discord server, so you can get notifications for updates there (https://github.com/samuelthomas2774/nxapi/issues/12).

**Comment by MCMi460** [comment]
Commit 51654f5d4c039dfe60b8b711d114265e892f6845 should fix this issue, I'm compiling release v1.3.1 right now.

**Comment by MCMi460** [comment]
v1.3.1 is now released and fixes #29 for both MacOS and Windows versions.
