### ISSUE TITLE
Switching games doesn't work/takes a long time to update

### ISSUE THREAD

**Issue by MCMi460** [MCMi460/NSO-RPC#3]
This is a common bug in the current version (tag v1.0) of the app.

It is not limited to any specific operating system, nor is it limited to the GUI.
However, it is only partially a bug. The current minimum update time of the app is 55 seconds (save for some manual conditions). This issue, instead, a feature request for shorter times.

Some caveats to this:
- Heavier 3rd-party API usage
- Possibly more suspicious API calls to Nintendo

The goal of this issue is to accomplish adding shorter refresh times **without any/most of the disadvantages**.

**Comment by MCMi460** [comment]
This should be mostly fixed now. Both of the caveats seem to be avoided by using `/v3/User/ShowSelf` method instead of constantly logging in and regenerating an `f` token like I used to.
Thanks to @samuelthomas2774 for the suggestion. Check out his Github repositories, as well!

**Comment by frozenpandaman** [comment]
>[Lower heavy usage of 3rd-party API / [d85286d](https://github.com/MCMi460/NSO-RPC/commit/d85286dd6646ec666e743a03ffa9cf68260509d2)

Thanks! @MCMi460 The logs show that – currently – there's ~5 users who are constantly sending requests over and over and over. I'm guessing they're actively running the program and something is going wrong. Can you check to make sure the code's not set up to do this? I've had to ban their IPs; other users are getting rate limit messages and unable to use the API.
