### ISSUE TITLE
Says I'm offline all the time.

### ISSUE THREAD

**Issue by Papscal** [MCMi460/NSO-RPC#31]
The program can see my friends and what they are playing, but my own status won't be updated.

**Comment by MCMi460** [comment]
Issue #26, #16, and #13 already address this. It's actually written in the guide on the README.md how to use this app.

**Comment by Papscal** [comment]
Ow i'm sorry I didn't look at that.

**Comment by MCMi460** [comment]
Ah, sorry about not making it more clear.
Sorry for the inconvenience!
