### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by kelvintoogood** [MCMi460/NSO-RPC#33]
Hey. I was able to launch the program just fine the last few days but today, I get the below launch error. Only other time I got an error that looked like this was last month, and that got fixed with the newest update due to the NSO app being updated. Is that the case again or is something wrong on my end, or something else? Thanks
![Q3ksrko](https://user-images.githubusercontent.com/111711710/185814368-474c94d3-c325-4e40-9ad3-e41c38da3f63.png)

**Comment by samuelthomas2774** [comment]
The flapg API was down earlier, it's back up so try again now...

@MCMi460 splatnet2statink switched to the imink API today so you'll need to migrate to that/something else as well soon.

**Comment by kelvintoogood** [comment]
Yeah it works now. Thanks

**Comment by MCMi460** [comment]
@samuelthomas2774 Thank you, will do right now. I see there are some interesting responses from Nintendo servers (code 9599s), so I'm hoping that switching to the imink API will fix those. Thanks again!

**Comment by MCMi460** [comment]
No, turns out this is more related to the timestamp part of the Nintendo API request. I'm moving this to #34.
