### ISSUE TITLE
Keep craching

### ISSUE THREAD

**Issue by LewiFF** [MCMi460/NSO-RPC#35]
when i try to open in it says
Launch error
Launch error See the py2app website for debugging launch issues
If you can help thank you

**Comment by zr0fve** [comment]
Same issue I'm having 
![image](https://user-images.githubusercontent.com/84481418/187032793-c9f171cf-1a40-4497-8a45-453fbd716a36.png)

**Comment by MCMi460** [comment]
Seems to be an issue with imink API.
I'm unaware as to why it is returning an HTML document with an error screen instead of the normal `f` token generation. Perhaps it is down?
Until I get a response about this issue, I can't really help just yet. Sorry about this.

**Comment by MCMi460** [comment]
Alright, this should be fixed now. Thanks for your patience!
