### ISSUE TITLE
CLI returning 'result' and exiting.

### ISSUE THREAD

**Issue by 2Epik4u** [MCMi460/NSO-RPC#39]
I logged in with an account that only has me added, and copied the link then it just returns 'result' and exits. When I use the GUI it simply doesn't open when i copy the link and enter.
![image](https://user-images.githubusercontent.com/28193089/189211056-29bf1c47-f117-49c1-abf8-b968b7cb1899.png)

**Comment by 2Epik4u** [comment]
the GUI seems to work after i logged in with the cli.

**Comment by MCMi460** [comment]
How strange. I'm glad it worked out, though. `'result'` being a response just means there is an issue with receiving login information from `/v2/Account/Login`, but because I'm dumb and lazy, I haven't coded in a better way of catching errors and relaying the information.
