### ISSUE TITLE
Not able to run on MacOS after first time

### ISSUE THREAD

**Issue by ElLucioVpe** [MCMi460/NSO-RPC#40]
I was able to launch the app just fine the first time but now I get this:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/29935787/189240623-5e0b1aff-4df5-490f-b472-ae31548536e0.png">

When running cli.py directly I get this:

```
> python cli.py 
  File "cli.py", line 134
    def getToken(manual = True, path:str = os.path.expanduser('~/Documents/NSO-RPC/private.txt')):
                                    ^
SyntaxError: invalid syntax
```

I'm not a Python developer so let me know if I'm running the command correctly or if you need any other debug information

**Comment by MCMi460** [comment]
That is certainly not incorrect syntax, so my assumption is that you're using macOS's default command for Python2.x which is `python`. Instead, try `python3 cli.py`.

**Comment by MCMi460** [comment]
And I have no idea why the errors are so inconsistent nowadays. It's strange; I can't tell what I've changed that causes such spontaneous failure.

**Comment by nitrogenfive** [comment]
I'm having this exact same issue. App launched initially, and after attempting to paste the authentication link, the app hung and then crashed. Refuses to open again even after uninstalling and reintalling.

**Comment by MCMi460** [comment]
One possibility is that PyPresence is hanging and preventing the app from working. I thought that I accounted for that in the code, but a user on the Discord server had the program freeze while trying to connect to Discord. A simple restart would fix it as it's an issue with piping, I believe, but other than that, my only guess is a failure in authentication, which appears to be the stem of every problem these days.
I've just pushed a commit (e2409dd9a0070ab5a4f3fa182f30e3ad1ae088da) that'll fix errors for all users, not just macOS. I'll update with a new release soon.

**Comment by MCMi460** [comment]
Please let me know if [v1.3.4](https://github.com/MCMi460/NSO-RPC/releases/tag/v1.3.4) fixes the issue.

**Comment by jrub1** [comment]
I'm also getting this issue, even with v1.3.4 :(

**Comment by MCMi460** [comment]
> I'm also getting this issue, even with v1.3.4 :(
> 
> 
> 
> EDIT: weird, restarting Discord fixed it. (on macOS)

There are a lot of strange, Discord-related errors when using this app, it seems. If you open up Discord Canary or PTB, different clients have different priorities to piping the presence, so it gets annoying in that regard. I'm going to make an update sometime soon-ish with a bunch of Settings menu updates, hopefully including a way to choose which Discord instance you want to use. Also, restarting your computer appears to work the majority of the time if it's a Discord-related issue. Not sure why. Maybe resetting something with PyPresence?

**Comment by MCMi460** [comment]
If no one else appears to be receiving this issue, I'm going to close it for the time being.
Please reopen/comment if you are having similar troubles.
