### ISSUE TITLE
Failed to execute script 'app' due to unhandled exception: 'result'

### ISSUE THREAD

**Issue by ScherHap** [MCMi460/NSO-RPC#42]
![image](https://user-images.githubusercontent.com/66132105/189820638-63e44a40-7a29-4288-9384-9fbf65583468.png)
I've had this issue before and when I reinstalled the app, it all worked again.
However, if I reinstall it now, nothing happens and it continues to show that error window on startup.
I have to add though, how do I actually fully uninstall the program? I always just deleted the .exe file but that's obviously not a full uninstall, as my login data and account is saved and used again when I 'reinstall' it.

**Comment by MCMi460** [comment]
Well, I'm not certain what is causing the app to fail logging in, but I can explain how to force remove your user data in case that may help fix the errors.
Try removing the `~/Documents/NSO-RPC/` folder. It'll be in the Documents folder inside of your user folder.

**Comment by QuandoSera** [comment]
I'm having the same problem; it was working fine a few days ago, and I'm not sure what's changed. I tried removing the '/Documents/NSO-RPC/' but I'm getting the same error after relinking the secondary account.

**Comment by QuandoSera** [comment]
I'm having the same problem; it was working fine a few days ago, and I'm not sure what's changed. I tried removing the `/Documents/NSO-RPC/` but I'm getting the same error after relinking the secondary account.

**Comment by MCMi460** [comment]
It's just failing to log in? The same exact `File "api\__init__.py", line 121, in updateLogin` thing?
I'm going to have to make a new release with better logging very soon. Have you tried running the app through the `app.py`?

**Comment by kibitser** [comment]
I'm having this same issue. It was working yesterday but not today. It's the same exact error, including the last line.

How do I run through app.py?

**Comment by caliswagilistic** [comment]
having the same issue currently. reinstalling doesn't fix it and neither does deleting the NSO-RPC folder.

**Comment by TotorRuns** [comment]
I also have the same issues as explained above.

**Comment by TotorRuns** [comment]
and running through app.py gave me this 
![image](https://user-images.githubusercontent.com/74136489/190855802-174be88a-5e42-489c-9004-6f4ef0a6d3cb.png)

**Comment by luisv555** [comment]
I put some debug print statements. I can see the authentication is failing, but I don't understand the auth flow to find a fix.
![image](https://user-images.githubusercontent.com/78295252/190884565-e7cb42a4-d99a-420e-913e-6fea276b5205.png)

**Comment by MCMi460** [comment]
The newest commit should fix the API issues. I've also added some better error logging, hopefully.
I'll compile and release a fix soon.

**Comment by TotorRuns** [comment]
I gonna give it a try if its released

Deltaion Lee ***@***.***> schrieb am So., 18. Sept. 2022,
21:46:

**Comment by MCMi460** [comment]
Please let me know if [v1.3.4](https://github.com/MCMi460/NSO-RPC/releases/tag/v1.3.4) fixes the issue.
I'm sorry for the inconvenience.

**Comment by TotorRuns** [comment]
Yeah i gonna inform you if its fixed

**Comment by TotorRuns** [comment]
yeah it works now

Thanks

**Comment by TotorRuns** [comment]
![image](https://user-images.githubusercontent.com/74136489/191434442-bc11880e-f892-47f3-9023-b0a441c4d2cc.png)
is it normal that it dont update the status if u are offline

**Comment by MCMi460** [comment]
@TotorRuns Yes, it is. Your status will appear blank until you begin to play a game.
