### ISSUE TITLE
Too many requests being sent to s2s API

### ISSUE THREAD

**Issue by frozenpandaman** [MCMi460/NSO-RPC#5]
>Lower heavy usage of 3rd-party API / [d85286d](https://github.com/MCMi460/NSO-RPC/commit/d85286dd6646ec666e743a03ffa9cf68260509d2)

Hi @MCMi460, thanks for this recent change.

However, the logs show that – currently, as I'm typing this – there's 5 users who are constantly sending requests over and over and over, totaling thousands of requests over the past few hours. This behavior has been seen since the user agent has been updated to 0.2. I'm guessing they're actively running the program and something is going wrong. Can you check to make sure the code's not set up to do this? I've had to ban their IPs; other users are getting rate limit messages and unable to use the API.

**Comment by frozenpandaman** [comment]
Note that you don't need to re-login (aka no need to `updateLogin()` and `requests.post()` the APIs) even once every 60 minutes – session tokens that are returned from calling the s2s+flapg API call are usually good for multiple hours, and in many cases even days. I don't know exactly what causes them to expire, but (and this is how splatnet2statink works too) they definitely should _only_ be refreshed upon login fail, not automatically after a set amount of time without trying to use them first.

**Comment by frozenpandaman** [comment]
Just to show one example of what's going on here…
![image](https://user-images.githubusercontent.com/7245874/161215678-cb43afae-debd-4deb-9833-e38f2c8f7e0b.png)

The API can handle one client doing this, but when it's every user simultaneously it clogs up the API and makes it unusable for others, including actual splatnet2statink users. Plus really uses up a ton of my personal bandwidth.

**Comment by samuelthomas2774** [comment]
> Note that you don't need to re-login (aka no need to `updateLogin()` and `requests.post()` the APIs) even once every 60 minutes – session tokens that are returned from calling the s2s+flapg API call are usually good for multiple hours, and in many cases even days. I don't know exactly what causes them to expire, but (and this is how splatnet2statink works too) they definitely should _only_ be refreshed upon login fail, not automatically after a set amount of time without trying to use them first.

The token used to access the app API is valid for exactly two hours. [I've documented most NSO app tokens here](https://gitlab.fancy.org.uk/samuel/nxapi/-/wikis/Nintendo-tokens) - they're mostly JSON Web Tokens. ([See my last comment on Reddit.](https://www.reddit.com/r/NintendoSwitch/comments/tpzabb/introducing_nsorpc_an_app_that_shows_what_switch/i2kk9ny/))

I've had a look at the code and can't tell why a hash could be requested every update (I don't know Python though). Maybe it's crashing and being restarted by a service manager?

**Comment by samuelthomas2774** [comment]
I've just discovered a separate endpoint, `/v3/Account/GetToken`, is used to refresh the token (with a new id_token from accounts.nintendo.com) if a request results in a token expired error. This isn't too helpful for us as it still requires an `f` token though. The request/response is exactly the same as `/v3/Account/Login` except the request doesn't include `naCountry` or `language`, but does include the old (expired) token in the Authorization header (I'm guessing that's just because a token already exists in the app and the server ignores it).

**Comment by MCMi460** [comment]
> > Lower heavy usage of 3rd-party API / [d85286d](https://github.com/MCMi460/NSO-RPC/commit/d85286dd6646ec666e743a03ffa9cf68260509d2)
> 
> Hi @MCMi460, thanks for this recent change.
> 
> However, the logs show that – currently, as I'm typing this – there's 5 users who are constantly sending requests over and over and over, totaling thousands of requests over the past few hours. This behavior has been seen since the user agent has been updated to 0.2. I'm guessing they're actively running the program and something is going wrong. Can you check to make sure the code's not set up to do this? I've had to ban their IPs; other users are getting rate limit messages and unable to use the API.

After looking through the code, I couldn't find any instances where it might repeatedly spam your service; I'm sorry I can't be of any more help.
As for the token expiration, like @samuelthomas2774 stated, the token expires exactly every 7200 seconds (or two hours). I set it to be every one hour because I wasn't sure of any possible clauses in which the program might miss an update and error out. I might have gone a bit overboard with this catch, and I like your idea of just checking for an error from Nintendo's API, so I'll implement that instead.

**Comment by samuelthomas2774** [comment]
@MCMi460 You should also save the token so you don't need to get a new one if the script is restarted. How I've done this is:

1. On startup, check to see if a token exists for the selected user and hasn't expired (by checking the local time when issued + token validity time).
2. If not, get a new token and save it.
3. On every update, if the status field in the response is `9404` (token expired) get a new token, save it and start the next update immediately. (I'll update this step to use `/v3/Account/GetToken` to match Nintendo's app, but I don't really think this is that important.)

That way if the process exits (either crashes or is stopped) you don't have to get a new token (and call s2s/flapg). This should prevent excessive login requests if it does crash and is set to restart automatically. splatnet2statink works differently as it can't check if the iksm_session cookie has expired at startup without just trying to use it, and doesn't need to get a new cookie after as any request will reset it's lifetime to a day.

**Comment by MCMi460** [comment]
@samuelthomas2774 Thank you so much for telling me this- you're genius!

**Comment by MCMi460** [comment]
If this is no longer a problem, I will be closing this issue. Please reopen it if there are still any problems occurring.
Thank you for bringing this to my attention and giving great suggestions!

**Comment by frozenpandaman** [comment]
> I've documented most NSO app tokens here

Thanks @samuelthomas2774, this is really helpful, and good to know!
