### ISSUE TITLE
[Request] Start with Windows in tray

### ISSUE THREAD

**Issue by Dekirai** [MCMi460/NSO-RPC#50]
Hey there, I recently found out about this amazing program, been looking for something like this for over a year!
It works perfectly fine on my end but I got one small request that may can be added in the future.

Add an option to start the program with windows and hide it in the tray, so you don't have to run the program everytime when you decide to play on your Switch!

Greetings

**Comment by Jenni32222** [comment]
Would be amazing if this was added

**Comment by Abro61209** [comment]
This would be a useless feature considering the thing stops working if you leave it running for more than 48 hours. I have to re-launch the client every time after that long so my status can actually reflect in discord. It seems if you don't play your switch for a few days it ends communications with Nintendo and you need to re-launch the client.

That needs to be fixed first then they can add "launch at startup".

**Comment by HotaruBlaze** [comment]
> This would be a useless feature considering the thing stops working if you leave it running for more than 48 hours. I have to re-launch the client every time after that long so my status can actually reflect in discord. It seems if you don't play your switch for a few days it ends communications with Nintendo and you need to re-launch the client.
> 
> That needs to be fixed first then they can add "launch at startup".

This is most likely an issue with the discord code, or the app losing access to discord and would be unrelated/handled in a different issue to this.

**Comment by Dekirai** [comment]
Closing since it has been added as of commit https://github.com/MCMi460/NSO-RPC/commit/83cf2cfec781d702ea6be7bfc728d5e25f958e72.
Thanks!
