### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by keremcyr9** [MCMi460/NSO-RPC#58]
![image](https://user-images.githubusercontent.com/62286481/211678652-4ddaa5fc-f092-4dc0-ae0f-6a0226cf067a.png)
so this happened again

**Comment by keremcyr9** [comment]
Maybe the api might be down or soemthing?

**Comment by samuelthomas2774** [comment]
The imink API (required for authentication) is currently down: https://status.imink.app.

**Comment by keremcyr9** [comment]
Okay thanks alot!

**Comment by MCMi460** [comment]
Now that it is up and working, I will be closing this issue. Please file a new one for any similar troubles with connectivity.
Thank you!
