### ISSUE TITLE
Discord Status doesn't work

### ISSUE THREAD

**Issue by OctoFloofy** [MCMi460/NSO-RPC#6]
For some reason the Discord Status is never appearing while the program is running. It does show as active in the tray but even while playing it never appeared.

**Comment by MCMi460** [comment]
When you run `cli.py` or `app.py`, do you get any errors as a result?

**Comment by OctoFloofy** [comment]
ok nevermind, i redownloaded the program and now it seems to work, but now if i play Mario Kart 8 in online mode the status just disappears once i load into a match.

**Comment by MCMi460** [comment]
That's strange, can you give any more information on it?
As far as I know, this is the only instance of that ever occurring.

**Comment by MCMi460** [comment]
I see the problem now. I was unaware previously that other `Presence().state`s existed. I'll update this now.
Thank you for bringing this to my attention!
