### ISSUE TITLE
[Linux] Something to add.

### ISSUE THREAD

**Issue by Po-rygon** [MCMi460/NSO-RPC#60]
when I enter /NSO-RPC/client and try to run app.py (python3 app.py) i get this: ModuleNotFoundError: No module named 'qtpy' and the GUI does not show up. 

Recomendation: add 'pip install qtpy' to the installation script.

**Comment by MCMi460** [comment]
You shouldn't need `qtpy` for this project, though. I'm confused as to why that error is appearing.
It may have something to do with your system distribution's implementation of Qt? What distro are you using?
I, personally, have only tested Ubuntu Kinetic Kudu.

**Comment by HotaruBlaze** [comment]
this seems more likely to be that pip install wasn't used or errored that was missed

**Comment by HotaruBlaze** [comment]
Confirmed to be receiving the `ModuleNotFoundError: No module named 'qtpy'` error on a fresh install of Ubuntu 22.04

**Comment by HotaruBlaze** [comment]
Handled and explained a little better in: https://github.com/MCMi460/NSO-RPC/pull/61

**Comment by MCMi460** [comment]
All working now on development branch. Thank you, @HotaruBlaze!
