### ISSUE TITLE
is a virus (real)

### ISSUE THREAD

**Issue by okzyrox** [MCMi460/NSO-RPC#7]
backdoor smhsmh

(to anyone reading, no it isn't a backdoor. he just messed up windows port or something)
![unknown-41](https://user-images.githubusercontent.com/79484310/161967956-c6c2050e-80e6-4341-bbd3-71656eb8b7a4.png)
![unknown-14](https://user-images.githubusercontent.com/79484310/161967982-e0ea6ad9-fe7a-41a5-a120-dd42dff1932c.png)

**Comment by okzyrox** [comment]
ok it was resolved

**Comment by MCMi460** [comment]
Anyone who is wondering more about this, I believe it's a fairly common [pyinstaller](https://pypi.org/project/pyinstaller/) bug.
Once again, if you have any doubts, I highly suggest you build yourself from the instructions in the [README](https://github.com/MCMi460/NSO-RPC/#building), or just run `cli.py` or `app.py` manually.
