### ISSUE TITLE
App showing twice in hidden icons

### ISSUE THREAD

**Issue by dreamy32** [MCMi460/NSO-RPC#71]
The app is showing twice in hidden icons when running in background. Are two instances running at the same time?

**Comment by MCMi460** [comment]
Are you referring to the tray icons? If so, then yes, two tray icons means that two instances of the app are running at the same time. You should right click and close one of them, though I don't know if that matters too badly.

**Comment by HotaruBlaze** [comment]
Its possible to run two instances, theirs no locks to prevent it, however running multiple instances is pretty pointless...

if it's happening with a single instance, then we'd have to know more info about what build and OS you are using.

**Comment by MCMi460** [comment]
Without any further information, I'm going to close this issue. Please open it again if you have any questions or continuing problems, or file a new one.
