### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by DamiWL** [MCMi460/NSO-RPC#73]
I did everything that's written in the guide, but i encounter a problem. I extracted the app, run it and pasted the account link. The app just closed, there was no icon in system tray. I tried opening again and got this error shown in the screenshot
![Bez tytułu](https://github.com/MCMi460/NSO-RPC/assets/134240525/495010c0-3b89-4377-9ffd-7267851f2489)
Deleting the folder in documents lets me run the app again, but the problem comes back after linking an account.
Any solutions? I already tried running as administrator, turning off my antivirus/antimalware software, i don't know what to do.

**Comment by MCMi460** [comment]
The account that you use has to have been used on a Nintendo Switch console at least once before. This error is signaling that the account you are linking does not have a link to a Nintendo Switch console. If this is not the problem, please let me know, but if it is, then simply just temporarily make a new user on your Nintendo Switch and link that account to it.

**Comment by DamiWL** [comment]
I didn't know that the friend account must be linked to the console, i did what you sugested and it works, thank you!

**Comment by Lohraa** [comment]
Hi, I have the same problem but I did link an account that is linked to the console, what do i do????

**Comment by HotaruBlaze** [comment]
This error is to do with you never loading the account on a Nintendo switch (This should be added somewhere as a note/requirement in the quick start)

**Comment by MCMi460** [comment]
> This error is to do with you never loading the account on a Nintendo switch (This should be added somewhere as a note/requirement in the quick start)

I hadn't an idea that it was even a problem beforehand, as I did not think that someone could even friend another user without first linking to a Nintendo Switch. Theoretically, I'm still not even sure if that's possible. No, seriously, how do you friend someone without a Nintendo Switch? The mobile app, which is the only other method of friending people, doesn't work without a Nintendo Switch linked, right?
Am I missing something glaringly obvious here?

**Comment by HotaruBlaze** [comment]
> > This error is to do with you never loading the account on a Nintendo switch (This should be added somewhere as a note/requirement in the quick start)
> 
> I hadn't an idea that it was even a problem beforehand, as I did not think that someone could even friend another user without first linking to a Nintendo Switch. Theoretically, I'm still not even sure if that's possible. No, seriously, how do you friend someone without a Nintendo Switch? The mobile app, which is the only other method of friending people, doesn't work without a Nintendo Switch linked, right? Am I missing something glaringly obvious here?

I just made a blank Nintendo account, after logging in I got the following window (Note this is android so IOS may act different)
So it's hard to believe that its possible to friend someone without using a switch.

![Screenshot_20230526-165334](https://github.com/MCMi460/NSO-RPC/assets/17028801/28953893-709b-4c1b-b390-f0510b222c17)
