### ISSUE TITLE
Unhandled Exception in Script (FIXED)

### ISSUE THREAD

**Issue by GawrShizu** [MCMi460/NSO-RPC#74]
I know that this already has 2 issues Tabs but mine seems a bit different from the others.
When i Log in with my Secondary Account (yes its linked on my Switch) the NSO-RPC app crashes.
![image](https://github.com/MCMi460/NSO-RPC/assets/107644617/477a0444-1d6a-4c3b-95f7-4c2ff47cc5cc)
![image](https://github.com/MCMi460/NSO-RPC/assets/107644617/243c0782-cb6e-4a7f-8278-2cc5b532a196)
(Same result when loggin into my Main account)
(Im on Windows 11)

**Comment by xelnaga74** [comment]
I'm having the same "Invalid token" issue. I had been using the app for a few days without problems.

**Comment by GawrShizu** [comment]
> I'm having the same "Invalid token" issue. I had been using the app for a few days without problems.

alright gives me a bit of hope that its not a problem on my end

**Comment by NekomataGami** [comment]
I also got the same error, was working fine a few hours ago, now I can't even launch the app anymore.

![image_379](https://github.com/MCMi460/NSO-RPC/assets/31979501/39f696a1-908c-4d38-9ea4-1df344f34c6c)

**Comment by GawrShizu** [comment]
> I know that this already has 2 issues Tabs but mine seems a bit different from the others. When i Log in with my Secondary Account (yes its linked on my Switch) the NSO-RPC app crashes. ![image](https://user-images.githubusercontent.com/107644617/240493882-477a0444-1d6a-4c3b-95f7-4c2ff47cc5cc.png) ![image](https://user-images.githubusercontent.com/107644617/240493919-243c0782-cb6e-4a7f-8278-2cc5b532a196.png) (Same result when loggin into my Main account)

Im on Windows 11 if thats helpful

**Comment by HotaruBlaze** [comment]
their is currently two issues going on, so I'm hoping this deals with any more issues that should popup.

Currently:
1) imink is having API issues and going offline, this is sometimes providing a timestamp error.

_**Below is the current major issue that this issue is affected by.**_
2) Nintendo seems to have broken/changed F-token generation with their latest update, meaning this is currently broken, and returning "Invalid token.".

So the app is currently unable to login to Nintendo correctly.

**Comment by Glitchmaster101** [comment]
I am also getting the same error;

**Comment by HotaruBlaze** [comment]
This is also currently broken on s3s that gives more info on the issue at hand, and its looking like this was fully intentional by Nintendo.
https://github.com/frozenpandaman/s3s/issues/125

**Comment by HotaruBlaze** [comment]
NSO-RPC should be working again, however you may get some timestamp errors when launching the program, for now when that happens, just close and open the program again. 

This may take multiple attempts due to downtime issues on imink: https://status.imink.app/

**Comment by MCMi460** [comment]
Now that this should be fixed, I will close this issue. Thank you, @HotaruBlaze for all of your help in this situation!
If any issues persist, please either comment on this issue or create a new one.
