### ISSUE TITLE
Unhandled Exception in Script 'Timestamp'

### ISSUE THREAD

**Issue by Ricy40** [MCMi460/NSO-RPC#76]
![image](https://github.com/MCMi460/NSO-RPC/assets/60597171/3b30a7d0-2ddc-4f95-80b9-1610236475d6)
Every time Iaunch it I get this now, it was working fine, issue just started.

**Comment by HotaruBlaze** [comment]
Please see this: https://github.com/MCMi460/NSO-RPC/issues/74#issuecomment-1562642908

**Comment by MCMi460** [comment]
This may still occur, but so long as closing the app and reopening works viably, then I'll be closing this issue for now as it is not one with NSO-RPC but rather its provider service, imink.
If this issue persists, please reopen this issue or file a new one.
Thank you!
