### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by pelicanfuture** [MCMi460/NSO-RPC#8]
Would be great if you could make a Linux version of this app as I only run Linux on my PC.
I could help test the app if you would like.
Thanks!

**Comment by MCMi460** [comment]
Sure! I'm not exactly how to compile Python for Linux, but if there's a good library for that, I'd love to try it out!
Send me a friend request on Discord at Delta#4444 and we can figure it out.

Thanks,
Delta
