### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by vvv112** [MCMi460/NSO-RPC#83]
<img width="420" alt="Screenshot 2023-06-15 at 13 35 27" src="https://github.com/MCMi460/NSO-RPC/assets/65280795/b0a1ecb6-b69b-47b9-89db-44a2e3c80b4c">

MacOs Catalina 10.15.7

Portable and installer

**Comment by RepressedNerd** [comment]
I've also got this issue!

**Comment by HotaruBlaze** [comment]
We need more info to get anywhere with errors like this

**Comment by HotaruBlaze** [comment]
> I've also got this issue!

Can you please install the "mac-installer.dmg" version and after installing, run the following command in your terminal
`/Applications/NSO-RPC.app/Contents/MacOS/NSO-RPC`

**Comment by vvv112** [comment]
> Can you please install the "mac-installer.dmg" version and after installing, run the following command in your terminal `/Applications/NSO-RPC.app/Contents/MacOS/NSO-RPC`

yes, i will try it soon
