### ISSUE TITLE
Unable to get Nintendo Account Link

### ISSUE THREAD

**Issue by YamiVKD** [MCMi460/NSO-RPC#94]
I have created a 2nd account, friended my main account. All good so far.
I log in to either account and it takes be straight to the user information page, it does not ask me to select like the image shows and nowhere can I find a way to that screen to get the link. Either your instructions is missing steps or something is set up wrong on my side but I cannot continue and this is super frustrating.

**Comment by MCMi460** [comment]
You mean straight to your user info? As in, straight to the logged-in profile? If so, then you've already completed the step where you need to login, but if you'd like to login again to a different account, then you can do so by clicking on "Settings" and clicking on "Logout".
This is what I think you're seeing:
![Screenshot 2023-07-19 at 10 28 46 PM](https://github.com/MCMi460/NSO-RPC/assets/32529306/e4c11e28-a8ff-4396-b101-eff151a171c9)
Please correct me if I am misunderstanding you.
If I'm not misunderstanding you, then the next step is to click on your friends list, find the target account, view their profile, and then click "Select Profile".

**Comment by YamiVKD** [comment]
You have misunderstood me, sorry if I was not clear. I'm still trying to link in my account. I open NSO-RP, It asks me to put in a link. So like the instructions say I open my browser, go to accounts.nintendo.com then I log in. Then that takes me to my User Information page, 
![image](https://github.com/MCMi460/NSO-RPC/assets/140036229/e0fdca5e-467d-4b64-8294-4905b8750eef)
But the instructions says I should be asked to choose a user/account and rightmouse to get the link but I do not get that page.

**Comment by MCMi460** [comment]
Ah, I see. That is odd...
Is the URL in the search bar still formatted like this: `https://accounts.nintendo.com/connect/1.0.0/authorize?client_id=71b963c1b7b6d119&redirect_uri=npf71b963c1b7b6d119%3A%2F%2Fauth&response_type=session_token_code&scope=openid+user+user.birthday+user.mii+user.screenName&session_token_code_challenge=[example]&session_token_code_challenge_method=S256&state=[example]&theme=login_form`?
Or does it just look like `https://accounts.nintendo.com/`?

**Comment by MCMi460** [comment]
Oh wait, I misread.

**Comment by MCMi460** [comment]
Sorry, when it says "enter a link", the application should automatically open your web browser with the "Select this account" page. Perhaps try closing the app and re-opening it?

**Comment by YamiVKD** [comment]
My browser was not opening. running the NSO-RPC application as administrator let it open the browser window. It was not opening the browser window automatically. It was just sitting there waiting for a link that I couldn't figure out how to get to.

**Comment by MCMi460** [comment]
Huh, that's odd.
Commit 9c8774f009769e4dc121d1cd6e87932a165cc807 kinda addresses this and makes it work by giving the user a link to click to access the same auth page if the `webbrowser` module on Python fails. This was something that I intended to add a while ago, but I forgot about it. Sorry for the inconvenience!
Other than that, is the program now working?

**Comment by YamiVKD** [comment]
Yes, it is working great. Thanks for your work.

**Comment by MCMi460** [comment]
Thank you, I'm glad it is working now!
