### ISSUE TITLE
fix linux support for ChromeOS (SOLVED)

### ISSUE THREAD

**Issue by circlesymbol** [MCMi460/NSO-RPC#98]
hey. when i try to install the linux version (1.3.9), it throws multiple errors making it impossible to install

**Comment by MCMi460** [comment]
What errors are you getting?

**Comment by circlesymbol** [comment]
WARNING: The script pycodestyle is installed in '/home/circle/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script markdown_py is installed in '/home/circle/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script normalizer is installed in '/home/circle/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script qtpy is installed in '/home/circle/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script autopep8 is installed in '/home/circle/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

**Comment by HotaruBlaze** [comment]
those should be fine to ignore, that's just warnings, not errors

**Comment by circlesymbol** [comment]
so when i try to launch it,

circle@penguin:~/NSO-RPC/client$ python3 app.py
Traceback (most recent call last):
  File "/home/circle/NSO-RPC/client/app.py", line 3, in <module>
    from qtpy.QtCore import *
  File "/home/circle/.local/lib/python3.9/site-packages/qtpy/__init__.py", line 259, in <module>
    raise QtBindingsNotFoundError from None
qtpy.QtBindingsNotFoundError: No Qt bindings could be found

**Comment by circlesymbol** [comment]
i installed qt, and still get this

**Comment by HotaruBlaze** [comment]
the correct bindings should have been installed during the install script, would you be able to give us all of the install script output, these snippets are missing important parts including debug info.

**Comment by circlesymbol** [comment]
nvmd installed the wrong qt, but now i get this:

Traceback (most recent call last):
  File "/home/circle/NSO-RPC/client/app.py", line 748, in <module>
    writeSettings()
  File "/home/circle/NSO-RPC/client/app.py", line 168, in writeSettings
    with open(settingsFile, 'w') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/circle/Documents/NSO-RPC/settings.txt'

**Comment by circlesymbol** [comment]
this is on chromebook btw, but i also tried on ubuntu 20.04 (which was sucessful before on i think up to 1.3.7 or something, but now throws the exact same errors as well)

**Comment by HotaruBlaze** [comment]
knowing its a chromebook helps, you should be having issues with the code on ubuntu, i'd be shocked if it was broken(though 20.04 is pretty old and EOL now)

I'd recommend checking if `'/home/circle/Documents/NSO-RPC` is a valid directory, Its possible chromebook does not create/use a Documents folder

**Comment by circlesymbol** [comment]
i tried creating one as well, but really doesnt do anything, unless i have to go in to the files and manully pick the txt out and drop it into it, which il try rn

**Comment by circlesymbol** [comment]
ok i have now idea on where it is, or whats contained in it

**Comment by HotaruBlaze** [comment]
the file is created when the program runs, but its saying the directory it needs does not exist, it should create the NSO-RPC one, however it wouldn't make the Documents folder by default, so check if `/home/circle/Documents` exists

**Comment by circlesymbol** [comment]
i could try to unistall it, and just create the doccuments folder and reinstall it to see

**Comment by HotaruBlaze** [comment]
the installer wont make the folder because it was assumed default that it'd always exist

**Comment by circlesymbol** [comment]
honestly i might just go back to my ubuntu vm and just install an older version to see if that works

**Comment by HotaruBlaze** [comment]
> honestly i might just go back to my ubuntu vm and just install an older version to see if that works

You should be able to run the latest version, if that's failing, you should provide **all** the output from the linux.sh file, it will let us know what's actually failing instead of small chunks

**Comment by circlesymbol** [comment]
ok il try on my ubuntu vm, fully installed with the nessecary things to intall older versions, just a sec

**Comment by HotaruBlaze** [comment]
Tested a Fresh ubuntu2204 VM, got the following error
![image](https://github.com/MCMi460/NSO-RPC/assets/17028801/314c3f69-b194-4bd4-80e9-b324067fcd91)
Do the following `sudo apt install python3-pyqt5` and re-run the linux.sh file, and it should pass and give you something like the following
![image](https://github.com/MCMi460/NSO-RPC/assets/17028801/403ecd21-63fb-4d63-9433-da095331bd25)
And it should just work when you try and run NSO-RPC.

Note these instructions only work for Ubuntu 20.04

**Comment by circlesymbol** [comment]
any way for chromebook, as it doesnt do doccuments automatically, as idk if debain 11 does that

**Comment by HotaruBlaze** [comment]
do the following command on chromebook, `mkdir ~/Documents`

**Comment by circlesymbol** [comment]
after creating the doccument folder, it still didnt make the folder 

[https://imgur.com/a/ggl8WIi](url)

**Comment by HotaruBlaze** [comment]
Might be a chrome OS bug, Documents might be stored differently on chromebook

**Comment by circlesymbol** [comment]
how would i manually add it?

**Comment by HotaruBlaze** [comment]
OK, so I've made a modified build of NSO-RPC that I believe is going to hopefully fix this.

1. Delete the existing NSO-RPC folder
2. Get the linux.sh file from here: https://github.com/HotaruBlaze/NSO-RPC/releases/tag/v1.3.10-PortableBuild
3. run the following command: `./linux.sh portableMode`, This will tell it to pull the portable branch
4. now run the following code: `touch ./NSO-RPC/client/portable`, NSO-RPC will try and use the same folder the code is stored in if it see's a file called `portable` beside `app.py `

Then attempt to run the application like normal, if its working, instead of trying to access the documents folder, you should have a folder called `NSO-RPC_Data` beside app.py and the rest of the source code.

**Comment by circlesymbol** [comment]
instead of running `./linux.sh portableMode`, could i run `bash linux.sh portableMode`? would it still run the same?

**Comment by HotaruBlaze** [comment]
Yep, it's the same thing

**Comment by circlesymbol** [comment]
It Works Perfectly! it actually runs now with no errors!
[https://imgur.com/a/grdlD3K](url)
